baseurl: https://kvasq.netlify.app/
title: Kevin Vasquez
author: Kevin Vasquez
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Kevin Vasquez
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/KVasq
      weight: 3
    #- name: Twitter
    #  url: https://twitter.com/nanxstats
    #  weight: 4
    #- name: Subscribe
    #  url: /index.xml
    #  weight: 5
